version: '3.1'

services:
  web:
    build: .
    container_name: koueki
    image: koueki:latest
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=koueki
      - POSTGRES_PASSWORD=postgres
      - MIX_ENV=prod
      - INITIAL_USERNAME=koueki
      - INITIAL_PASSWORD=admin
      - ORG_NAME=koueki_org
    secrets:
      - config

  db:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - /data/koueki/db:/var/lib/postgres/data/
    environment:
      - POSTGRES_USER=koueki
      - POSTGRES_PASSWORD=postgres

secrets:
  config:
    file: config/prod.secret.exs
